export const metadata = {
  title: "Services",
  description: "Generated by create next app",
};

export default function Services() {
  return (
    <>
      <h1 className="text-2xl font-bold">Services</h1>
    </>
  );
}
